# NOTE: update this with your service name
service: strymer-core

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2

  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    listenNotesEnvVar: ${env:LISTEN_NOTES_API}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-2:*:*'

functions:
  list:
    handler: routes/list.main
    events:
      - http:
          path: podcasts
          method: get
          cors: true
          authorizer: aws_iam
  listFavorites:
    handler: routes/listFavorites.main
    events:
      - http:
          path: favorites
          method: get
          cors: true
          authorizer: aws_iam
  get:
    handler: routes/get.main
    events:
      - http:
          path: podcasts/{id}
          method: get
          cors: true
          authorizer: aws_iam
  create:
    handler: routes/createFavorites.main
    events:
      - http:
          path: favorites
          method: post
          cors: true
          authorizer: aws_iam
  delete:
    handler: routes/deleteFavorites.main
    events:
      - http:
          path: favorites/{id}
          method: delete
          cors: true
          authorizer: aws_iam
